### ISSUE TITLE
Clean 800-171 ansible remediation script won't parse, floating 't' and other issues surrounding pam_faillock

### ISSUE THREAD

**Issue by justchris1** [OpenSCAP/scap-security-guide#2841]
#### Description of problem:
Upon generating an ansible remediation script on the 800-171 profile on rhel7, the ansible script won't parse.  

#### SCAP Security Guide Version:
Master v0.1.40

#### Operating System Version:
Centos 7.5

#### Steps to Reproduce:

1. Git Clone (git clone https://github.com/OpenSCAP/scap-security-guide.git)
2. cd scap-security-guide; cd build
3. cmake ../
4. make -j4
5. open scap-workbench and load locally built xml: usr/local/share/xml/scap/ssg/content/ssg-centos7-ds.xml
6. select profile 800-171
7. click - generate ansible remediation script (before running the scan)

#### Actual Results:
Lines 4445 and 4578 do not parse.  The line is 't' which is not a valid command, obviously.

#### Expected Results:
The file passes parsing.

#### Addition Information/Debugging Steps:
I actually think that the lines above and below the 't' are a mistake and aren't meant to be there anyway.  I think lines 4442 through 4450 and repeated in lines 4575 through 4583 are a mistake.  The text (which is repeated twice) is below:

```
  - name: XCCDF Value var_accounts_passwords_pam_faillock_unlock_time # promote to variable
      set_fact:
        var_accounts_passwords_pam_faillock_unlock_time: never
      t
    - name: XCCDF Value var_accounts_passwords_pam_faillock_fail_interval # promote to variable
      set_fact:
        var_accounts_passwords_pam_faillock_fail_interval: 900
      tags:
        - always
```

I think this because a variable defined at the top of the file in the vars section already defines the two variables listed:

```
var_accounts_passwords_pam_faillock_unlock_time
var_accounts_passwords_pam_faillock_fail_interval
```

Finally, it seems that the two variables listed are actually listed twice, which is an error.  A user could set the variable and it actually gets overloaded on the second instance.  They are defined on lines 132-134 and again on 136-139.  This includes a third variable:
`var_accounts_passwords_pam_faillock_deny
`
that doesn't seem to have the same issue of the set_fact declaration further in the code, but does have repeated declaration.

Next, there is a parse error on lines 4452 to 4458, with an error that new_type can't be empty:
```
    - name: set auth pam_faillock before pam_unix.so
      pamd:
        name: system-auth
        type: auth
        control: sufficient
        module_path: pam_unix.so
        new_type: 
```
    
which seems to be a partial stanza which is repeated immediately below, with what I assume was the intended effect:
```
    - name: set auth pam_faillock before pam_unix.so
      pamd:
        name: system-auth
        type: auth
        control: sufficient
        module_path: pam_unix.so
        new_type: auth
        new_control: required
        new_module_path: pam_faillock.so
        module_arguments: 'preauth
            silent
            even_deny_root
            deny={{ var_accounts_passwords_pam_faillock_deny }}
            unlock_time={{ var_accounts_passwords_pam_faillock_unlock_time }}
            fail_interval={{ var_accounts_passwords_pam_faillock_fail_interval }}'
        state: before
      tags:
        - accounts_passwords_pam_faillock_deny_root
        - medium_severity
        - restrict_strategy
        - low_complexity
        - low_disruption
        - CCE-80353-6
        - NIST-800-53-AC-7(b)
        - DISA-STIG-RHEL-07-010330
```

Lastly, I am not a pam.d expert, but I am unsure if the accounts_passwords_pam_faillock_deny tag is actually nullifying the earlier accounts_passwords_pam_faillock_deny_root tag.  It seems like the first (deny_root) sets deny root, but it is removed in the 'accounts_passwords_pam_faillock_deny' tag sequence.  It seems like the code was trying to figure out a way to do either, but is actually inserting both and thus is essentially picking just 1 (the arbitrarily later one).  I would recommend using some type of variable to determine if even_deny_root should also be applied to faillock and insert it if needed (or set to empty so insertion each time is not a problem).  Of course, if I misunderstand the double entry in pam.d, I apologize.
